import Breadcrumbs from "@components/breadcrums";
import HeroBannerTitle from "@components/hero-banner-left-align";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen font-sans antialiased">
      <HeroBannerTitle
        imageUrl="/images/research/hero-banner.jpg"
        title="Research"
        subtitle="Explore our cutting-edge research initiatives, supported by state-of-the-art infrastructure and strengthened through collaborations with leading universities worldwide."
      />
      <Breadcrumbs />
      <main>{children}</main>
    </div>
  );
}
